// 
// Environment.cs
// 
// This file is auto-generated by Amplitude.
// To update run 'ampli pull visual-studio-plugin'
// 
// Questions? We're here to help:
// https://developers.data.amplitude.com/dotnet
// 

namespace Iteratively
{
    public enum Environment
    {
        Development,
        Production
    }
}