// 
// JsonSerializerFactory.cs
// 
// This file is auto-generated by Amplitude.
// To update run 'ampli pull visual-studio-plugin'
// 
// Questions? We're here to help:
// https://developers.data.amplitude.com/dotnet
// 

using System;
using Manatee.Json.Serialization;

namespace Iteratively
{
    internal static class JsonSerializerFactory
    {
        private static readonly JsonSerializerOptions options = new JsonSerializerOptions()
        {
            EncodeDefaultValues = true
        };

        public static JsonSerializer Create()
        {
            return new JsonSerializer()
            {
                Options = options
            };
        }
    }
}