// 
// Destinations/Custom.cs
// 
// This file is auto-generated by Amplitude.
// To update run 'ampli pull visual-studio-plugin'
// 
// Questions? We're here to help:
// https://developers.data.amplitude.com/dotnet
// 

using System;

namespace Iteratively
{
    public sealed class CustomOptions
    {
        public IDestination Adapter { get; }

        public CustomOptions(IDestination adapter)
        {
            if (adapter == null)
                throw new ArgumentNullException(nameof(adapter));

            Adapter = adapter;
        }
    }
}