name: Integration Tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TEST_API_TOKEN:
        required: true

jobs:
  test-vs22:
    continue-on-error: true
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Tests
      run: vstest.console.exe **\bin\**\*Integration.Tests.dll
