name: Integration Tests

on:
  workflow_call:
    secrets:
      TEST_API_TOKEN:
        required: true

jobs:
  test-vs19:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
    - name: Run tests
      uses: microsoft/vstest-action@main
      with:
        testAssembly: Integration.Pre22.Tests.dll
        searchFolder: .\Tests\Integration.Pre22.Tests\bin\Debug
        runInParallel: true

  test-vs22:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
    - name: Run tests
      uses: microsoft/vstest-action@main
      with:
        testAssembly: Integration.Tests.dll
        searchFolder: .\Tests\Integration.Tests\bin\Debug
        runInParallel: true