name: release for 2022

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2'  # every Tuesday at 10 am UTC

env:
  SOLUTION_FILE_PATH: .
  DEFAULT_BRANCH: main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }} 
    env:
      TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
        files: '.\Snyk.Common\appsettings.json'
      env:
        SegmentAnalyticsWriteKey: ${{ secrets.SEGMENT_ANALYTICS_WRITE_KEY }}
        SnykCodeApiEndpointUrl: ${{ secrets.SNYK_CODE_API_ENDPOINT_URL }}
        SentryDsn: ${{ secrets.SENTRY_DSN }}
        Environment: ${{ secrets.SENTRY_ENVIRONMENT }}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '[14.0, ]'

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
      shell: powershell

    - name: Tests
      run: vstest.console.exe **\*.Tests.dll

    - name: Publish 2022 extension to Marketplace
      uses: cezarypiatek/VsixPublisherAction@0.1
      with:
        extension-file: '.\Snyk.VisualStudio.Extension.2022\bin\Release\Snyk.VisualStudio.Extension.vsix'
        publish-manifest-file: '.\Snyk.VisualStudio.Extension.2022\vs-publish.json'
        personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
